# Generated by Django 6.0.3 on 2026-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da máquina')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço IP ou hostname')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='usuário')),
                ('log_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='caminho do arquivo de log')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='porta')),
                ('_password_encrypted', models.CharField(blank=True, db_column='password', max_length=500, null=True, verbose_name='senha criptografada')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
