# Generated by Django 6.0.3 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=22, verbose_name='porta'),
        ),
    ]
